# Generated by Django 5.2.10 on 2026-02-26 16:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField(blank=True)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "time_taken_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CandidateInterview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=100)),
                ("difficulty", models.CharField(max_length=20)),
                ("question_count", models.PositiveIntegerField(default=5)),
                ("candidate_email", models.EmailField(max_length=254)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("overall_score", models.FloatField(blank=True, null=True)),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_interviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("feedback", models.TextField()),
                ("improvement_tips", models.TextField()),
                ("ai_raw_response", models.JSONField()),
                ("evaluated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="interviews.answer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterviewTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=255)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=20,
                    ),
                ),
                ("question_count", models.PositiveIntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("coding", "Coding"),
                            ("audio", "Audio"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="interviews.candidateinterview",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answer",
                to="interviews.question",
            ),
        ),
        migrations.AddIndex(
            model_name="candidateinterview",
            index=models.Index(
                fields=["recruiter"], name="interviews__recruit_e98e00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidateinterview",
            index=models.Index(
                fields=["is_completed"], name="interviews__is_comp_804cc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidateinterview",
            index=models.Index(
                fields=["started_at"], name="interviews__started_f52cf0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evaluation",
            index=models.Index(fields=["score"], name="interviews__score_6af3e2_idx"),
        ),
        migrations.AddIndex(
            model_name="interviewtemplate",
            index=models.Index(
                fields=["recruiter"], name="interviews__recruit_eed633_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interviewtemplate",
            index=models.Index(
                fields=["created_at"], name="interviews__created_4453d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["interview"], name="interviews__intervi_4f5bc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["question"], name="interviews__questio_ed9cc9_idx"
            ),
        ),
    ]
