# Generated by Django 5.2.10 on 2026-02-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
