# Generated by Django 5.2.10 on 2026-03-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0003_add_candidate_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateinterview",
            name="candidate_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
